#!/bin/bash

echo "=========================================="
echo "🔄 RESET Y TEST DE CLASSROOM"
echo "=========================================="
echo ""

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Este script te ayudará a resolver el problema de carga de Classroom${NC}"
echo ""

echo "=========================================="
echo "📋 DIAGNÓSTICO DEL PROBLEMA"
echo "=========================================="
echo ""
echo "El error 401 Unauthorized indica que:"
echo "  • El login funciona correctamente ✓"
echo "  • Pero el token NO tiene permisos de Classroom ✗"
echo ""
echo "Esto sucede porque el token que obtuviste en el login anterior"
echo "no incluye los nuevos scopes de Classroom que acabamos de configurar."
echo ""

echo "=========================================="
echo "🔧 SOLUCIÓN"
echo "=========================================="
echo ""
echo "Necesitas hacer un NUEVO login para obtener un token con los"
echo "permisos correctos de Classroom."
echo ""

echo -e "${YELLOW}IMPORTANTE:${NC} Cuando hagas el nuevo login, Google te pedirá"
echo "permisos adicionales para acceder a Google Classroom."
echo "Debes aceptar TODOS los permisos."
echo ""

echo "=========================================="
echo "✅ PASOS A SEGUIR"
echo "=========================================="
echo ""

echo "1️⃣  Abre Google Cloud Console OAuth Consent Screen:"
echo "   ${BLUE}https://console.cloud.google.com/apis/credentials/consent?project=hackathon-2025-475302${NC}"
echo ""
echo "   Verifica que tenga estos scopes (en la sección 'Scopes'):"
echo "   ✓ openid"
echo "   ✓ .../auth/userinfo.email"
echo "   ✓ .../auth/userinfo.profile"
echo "   ✓ .../auth/classroom.courses.readonly"
echo "   ✓ .../auth/classroom.rosters.readonly"
echo "   ✓ .../auth/classroom.coursework.students.readonly"
echo "   ✓ .../auth/classroom.coursework.me.readonly"
echo "   ✓ .../auth/classroom.announcements.readonly"
echo ""
echo "   ${YELLOW}Si NO están todos, agrégalos:${NC}"
echo "   - Click en 'EDIT APP'"
echo "   - Click en 'SCOPES' → 'ADD OR REMOVE SCOPES'"
echo "   - Busca 'classroom' y marca TODOS los scopes readonly"
echo "   - Click en 'UPDATE' y luego 'SAVE AND CONTINUE'"
echo ""

echo "2️⃣  Verifica que tu email esté en Test Users:"
echo "   En la misma página, ve a la sección 'Test users'"
echo "   Tu email debe estar en la lista"
echo "   ${YELLOW}Si no está, agrégalo:${NC}"
echo "   - Click en 'ADD USERS'"
echo "   - Ingresa tu email"
echo "   - Click en 'SAVE'"
echo ""

echo "3️⃣  Reinicia el backend (para cargar los nuevos scopes):"
echo ""
echo "   ${GREEN}cd backend${NC}"
echo "   ${GREEN}source venv/bin/activate${NC}"
echo "   ${GREEN}uvicorn app.main:app --reload${NC}"
echo ""

echo "4️⃣  Reinicia el frontend:"
echo ""
echo "   ${GREEN}cd frontend${NC}"
echo "   ${GREEN}npm run dev${NC}"
echo ""

echo "5️⃣  En el navegador:"
echo ""
echo "   a) Abre DevTools (F12)"
echo "   b) Ve a Application → Storage → Clear site data"
echo "   c) O simplemente borra localStorage con:"
echo "      ${GREEN}localStorage.clear()${NC} en la consola"
echo ""
echo "   d) Ve a ${BLUE}http://localhost:5173${NC}"
echo "   e) Haz login de nuevo con Google"
echo ""
echo "   ${YELLOW}⚠️  IMPORTANTE:${NC}"
echo "   Google te mostrará una pantalla pidiendo permisos adicionales"
echo "   para acceder a Google Classroom. Debes aceptar TODOS."
echo ""
echo "   f) Una vez en el dashboard, abre la consola del navegador (F12)"
echo "      y la pestaña Network para ver las peticiones"
echo ""

echo "=========================================="
echo "🧪 VERIFICAR QUE FUNCIONA"
echo "=========================================="
echo ""
echo "Después del nuevo login:"
echo ""
echo "✓ Deberías ver tus cursos de Classroom"
echo "✓ Deberías ver tareas pendientes"
echo "✓ Deberías ver anuncios recientes"
echo ""
echo "Si NO funcionó, revisa:"
echo "  • Logs del backend: ${GREEN}tail -f backend_uvicorn.log${NC}"
echo "  • Consola del navegador (F12 → Console)"
echo "  • Network tab del navegador (F12 → Network)"
echo ""

echo "=========================================="
echo "❓ SI AÚN NO FUNCIONA"
echo "=========================================="
echo ""
echo "Posibles causas:"
echo ""
echo "1. La cuenta de Google no tiene cursos en Classroom"
echo "   → Crea un curso de prueba o únete a uno"
echo ""
echo "2. Los scopes no están en el OAuth Consent Screen"
echo "   → Verifica que TODOS estén agregados (paso 1)"
echo ""
echo "3. El email no está en Test Users"
echo "   → Agrégalo (paso 2)"
echo ""
echo "4. Google está usando caché de permisos"
echo "   → Revoca el acceso manualmente en:"
echo "   ${BLUE}https://myaccount.google.com/connections${NC}"
echo "   → Busca 'CALMA TECH' y elimínalo"
echo "   → Vuelve a hacer login"
echo ""

echo "=========================================="
echo ""
read -p "Presiona ENTER cuando hayas completado todos los pasos..."
